[tool.black]
line-length = 100
skip-magic-trailing-comma = true
extend-exclude = '''/venv'''

[tool.isort]
profile = "black"
line_length = 100
skip = [".gitignore", "venv", ".flake8", ".git"]

[tool.pydocstyle]
match-dir = '^(venv)'
match = '.*\.py'
convention = "google"
add-ignore = 'D100,D104'

[tool.mypy]
python_version = "3.9"
exclude = [
    "tests",
    "venv",
]
# --strict
disallow_any_generics = true
disallow_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
implicit_reexport = false
strict_equality = true
# --strict end

